name: nock
description: HTTP requests mocking library for dart and flutter. Test your application in isolation.
version: 1.2.1
homepage: https://github.com/cah4a/dart_nock

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  test: ^1.21.7
  collection: ^1.15.0

dev_dependencies:
  http: ^0.13.0
  pedantic: ^1.11.0
